### ISSUE TITLE
为什么不支持php？

### ISSUE THREAD

**Issue by zhaiyuyong** [baifendian/harpc#1]
php不是最好的编程语言么？为什么不支持

**Comment by dsfan** [comment]
我们内部对php的使用比较少，暂时没有对php支持的规划。

**Comment by matrix2011** [comment]
php 用户确实很多，不知道 @zhaiyuyong 是不是有兴趣一起开发开源？

**Comment by zhaiyuyong** [comment]
我主要做java的 我问问我们公司的php leader有没有兴趣参加
