### ISSUE TITLE
通过web端开启的server无法被删除？

### ISSUE THREAD

**Issue by HouLinwei** [baifendian/harpc#5]
如果通过本地直接启动服务端，在页面上是可以有“查看/删除”两个选项的。
但是一旦通过web的“+server”按钮添加之后，这个服务就没办法删除掉了（删除按钮不见了）。同时，在zookeeper中的地址 /harpc/service$name/servers/ip:port 是无法被rmr命令删除的。

我不理解这是设计上的问题，还是我操作不正确？

**Comment by caojingwei** [comment]
和zk写入权限有关系，看下settings.py里面的配置文件 zk用户是怎么配置的。

**Comment by HouLinwei** [comment]
配置的用户名密码是test/test， web账号是admin/admin。
- web上的删除按钮，我再次测试之后发现是可以删除了。但是确实有遇见没有删除按钮的情况。
- zookeeper上的节点，可以通过adduser digest test:test 删除。

如果确认系统设计无误，可以关闭此issue。

**Comment by dsfan** [comment]
设计上确实有权限控制。
