### ISSUE TITLE
RoundRobinStrategy里面使用的Iterators.cycle非线程安全

### ISSUE THREAD

**Issue by scguoi** [baifendian/harpc#7]
多线程执行时throw new ResourceExhaustedException("No backends available!");
会大量的发生。
[参考](http://stackoverflow.com/questions/4493643/guava-libraries-is-iterators-cycle-thread-safe)

**Comment by dsfan** [comment]
这个的确是非线程安全的，所以我们在调用的时候加了同步，参考：[LoadBalancerImpl](https://github.com/baifendian/harpc/blob/916426984190e0937922511d27b2c0bf18497b98/java/harpc/src/main/java/com/bfd/harpc/loadbalance/LoadBalancerImpl.java)。
